config/routes.rb
Rails.application.routes.draw do

  resources :archives, :except => :show
  get "/archives/download" => "archives#download", as: "archive_download"
  root :to => 'archives#new'

end

app/models/archive.rb
class Archive < ActiveRecord::Base
  has_many :documents, dependent: :destroy
  validates_presence_of :name
  validates_uniqueness_of :name
  accepts_nested_attributes_for :documents, allow_destroy: true, reject_if: Proc.new{|attrs| attrs[:main_file].blank? }

  
  def get_input_filenames
    archive = self
    input_filenames = {}
    archive.documents.each do |doc|
      input_filenames[doc.id] = doc.main_file_file_name
    end
    return input_filenames
  end


  def download_zip
    archive = self
    archive_name = archive.name
    
    folder = Rails.root.join("public","system")

    input_filenames = archive.get_input_filenames
    
    zipfile_name = Rails.root.join("public","zip","#{archive_name}.zip")
    filename = "#{archive_name}.zip"
    
    t = Tempfile.new("#{archive_name}.zip")

    Zip::File.open(zipfile_name, Zip::File::CREATE) do |zipfile|
      input_filenames.each do |doc_id, filename|
        # Two arguments:
        # - The name of the file as it will appear in the archive
        # - The original file, including the path to find it
        zipfile.add(filename, "#{folder}" + "/" +"#{doc_id}"+"/"+ "#{filename}")
      end
    end
    return zipfile_name
    
    t.close
  end
end

app/models/document.rb
class Document < ActiveRecord::Base
  belongs_to :archive

  has_attached_file :main_file
  
  validates_attachment :main_file, 
                        presence: true, 
                        content_type: { content_type: [ "image/jpeg", "image/png", "image/jpg", "text/csv", "text/html", "text/xml", "application/msword"] }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/archives_controller.rb
require 'rubygems'
require 'zip'
require 'tempfile'

class ArchivesController < ApplicationController
  include ApplicationHelper
  
  def index
    @archives = Archive.order('created_at desc').all
  end

  def new
    refresh=true
    @archive = Archive.new
  end

  def create
    @archive_attributes = params.require(:archive).permit!
    @archive = Archive.create(@archive_attributes)
    if @archive.errors.empty? && @archive.documents.present?
      begin
        @archive.get_input_filenames
        filename = "#{@archive.name}.zip"
        zipfile_name = @archive.download_zip
      
        send_file zipfile_name, :type => 'application/zip',
                                :disposition => 'attachment',
                                :filename => filename
      rescue Exception => e
        Rails.logger.info e
        redirect_to new_archive_path, alert: e
      end
    else
      msg = @archive.errors.present? ? @archive.errors.full_messages.join(" ") : "Please add atleast one document"
      redirect_to new_archive_path, alert: msg
      return
    end
  end

  def destroy
    archive = Archive.find(params[:id])
    zipfile_path = Rails.root.join("public","zip", "#{archive.name}.zip")
    FileUtils.rm_rf(zipfile_path)
    if archive.delete
      redirect_to archives_path, :notice => "Successfully deleted"
    else
      redirect_to archives_path, :alert => "Cannot delete"
    end
  end

  def download
    archive = Archive.find(params[:id])
    zipfile_name = Rails.root.join("public","zip", "#{archive.name}.zip")
    file_name = File.open(zipfile_name, 'rb')

    t = Tempfile.new("#{archive.name}.zip")
    filename = "#{archive.name}.zip"
    send_file file_name,  :type => 'application/zip',
                          :disposition => 'attachment',
                          :filename => filename
  end

  private

  def safe_params
    safe_attributes = [
      :name,
      documents_attributes: [
        :main_file,
        :_destroy
      ]
    ]
    params.require(:archive).permit(*safe_attributes)
  end

  
end

app/helpers/application_helper.rb
module ApplicationHelper
  def link_to_add_fields(name, f, association)
    new_object = f.object.send(association).klass.new
    id = new_object.object_id 
    fields = f.fields_for(association, new_object, :child_index => id) do |builder|
      render(association.to_s.singularize + "_fields", :f => builder)
    end
    link_to(name, "#",class: "add_fields", data: {id: id, fields: fields.gsub("\n", "")})
  end
end

app/views/archives/_document_fields.html.erb
<fieldset>
  <table class="table table-striped" width="100%">
    <tr>
      <td width="20%" ><%= f.file_field :main_file %>
      <%= f.hidden_field :_destroy %></td>
      <td width="80%" ><%= link_to image_tag('minus_alt.png'), '#', class: "remove_fields" %></td>
    </tr>
  </table>
</fieldset>

app/views/archives/index.html.erb
<h2>Listing Zip files</h2>
<table class="table table-hover">
  <thead>
   <tr>
    <th>Name</th>
    <th>Action</th>
    </tr>
  </thead>
  <tbody>
    <% @archives.each do |archive| %>
      <tr>
        <td><%= archive.name %></td>
        <td><%= link_to image_tag('download_icon.png'), archive_download_path(:id => archive.id), :data => { toggle: 'tooltip', placement: 'right', title: 'Download Zipfile'} %></td>
        <td><%= link_to image_tag('remove-icon.png'), archive_path(:id => archive.id), method: 'delete', :data => { toggle: 'tooltip', placement: 'right', title: 'Delete Zipfile'} %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/archives/new.html.erb
<%= simple_form_for(@archive, html: {class: 'form-horizontal',  role: "form"}) do |f| %>
  <fieldset>
    <div class="form-group">
      <div class="col-sm-8">
        <%= f.label :name, class: "col-sm-4" %>
        <%= f.text_field :name %>
      </div>
    </div>
    <%= f.fields_for :documents do |document| %>
      <%= render 'document_fields', f: document %>
    <% end %>
    <div class="form-group">
      <div class="col-sm-8">
        <%= link_to_add_fields image_tag('plus_icon.png'), f, :documents %></br></br>
      </div>
    </div>
    <%= f.button :submit %>
  </fieldset>
<% end %>
<script type="text/javascript">
$(document).ready(function() {
  $('#add_fields').click(function() {
    alert("dsds");
  });
});
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Dossier</title>
  <meta http-equiv=”refresh” content='5'>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= javascript_include_tag 'application', :cache => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <div class="row">
      <div class="nav navbar navbar-default">
        <div class="container-fluid">
          <div class="navbar-header">
            <a href="<%= archives_path %>" class="navbar-brand"> Archives</a>
            <ul class="nav navbar-nav">
              <li><a href="<%= new_archive_path %>" id="new_archive">Create New Archive</a></li>
            </ul>
        </div>
      </div>
    </div>
    <div class="content">
      <div class="panel">
        <% if alert.present? %>
          <div class="alert-danger">
            <p>
              <%= raw alert %>
            </p>
          </div>
          <div class="login_shadow">&nbsp;</div>
        <% end %>
        <% if notice.present? %>
          <div class="alert-success">
            <p>
              <%= raw notice %>
            </p>
          </div>
          <div class="login_shadow">&nbsp;</div>
        <% end %>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12">
        <%= yield %>
      </div>
    </div>
  </div>
</body>
</html>